spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart: #config upload file setting
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
---
app:
  token:
    secret: n#MySecretGGWP2021
    issuer: BackendService
  